### ISSUE TITLE
fatal error: 'microtar.h' file not found

### ISSUE THREAD

**Issue by clsource** [avivbeeri/nest#1]
when doing `make`

```
cc -std=c99 -pedantic -Wall -o nest src/main.c -Ilib/microtar/src -lm
src/main.c:11:10: fatal error: 'microtar.h' file not found
#include "microtar.h"
         ^~~~~~~~~~~~
1 error generated.
make: *** [nest] Error 1
```

**Comment by avivbeeri** [comment]
I've pushed a fix onto master which I hope fixes this issue. Could you give it a try?

**Comment by clsource** [comment]
Seems fine now 👍 

![imagen](https://user-images.githubusercontent.com/292738/97257023-786f8b80-17f3-11eb-9c69-fca66e2d2f33.png)
